### PR TITLE
docs: removing enumerable and enumerables from doc

### PR DESCRIPTION
**Pull request by vinassefranche**
Signed-off-by: Vincent Francois <vfrancois@fastbooking.net>

### CODE REVIEW

**Comment by btd** [comment]
Thank you. But docs are generated from sources. I could not accept this. Sorry.

**Comment by vinassefranche** [comment]
Hi!

Thanks for your quick answer.
Apparently there's a discrepancy today between the latest should version and the doc (the functions enumerable and enumerables appear in the doc while they are not present anymore in should) Is there anything I can do to help for the doc generation?

Regards

**Comment by btd** [comment]
I regenerated docs for fresh version, but it still needs some work.

**Comment by vinassefranche** [comment]
Ok. Great.
Thanks!

**Pull request closed without merging**
